export const initialState = {
  posts: {
    //data: {},
    data: [
      {id: 1, autor: 'adam@wp.pl', email:'adam@wp.pl', title: 'Lorem ipsum', created: new Date(2021,11,14,13,35), status: 'published', price:'15990.66', location:'Kraków', content: ' Integer aliquet sapien vel est efficitur convallis vitae et massa. Vivamus nunc quam, tincidunt quis posuere ac, rhoncus in justo. Curabitur at consequat augue. Nulla at leo et nunc consectetur pretium id mollis justo. Morbi eu tempor urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis augue id neque scelerisque, sed porttitor libero finibus. Sed et orci fermentum, convallis nulla sed, posuere metus. Fusce a consectetur magna. Mauris facilisis enim urna, et ultrices quam suscipit ac. ', image: 'https://www.wyborkierowcow.pl/wp-content/uploads/2020/11/Chevrolet-Spark-II-03.jpg'},
      {id: 2, autor: 'agnf@gmail.com', email:'agnf@gmail.com', title: 'Quisque metus', created: new Date(2021,11,13,18,35), status: 'published', content: 'Curabitur egestas sit amet massa id placerat. Etiam rhoncus ultrices ligula, eu ultricies tellus bibendum vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. In consequat scelerisque maximus. Praesent gravida leo sit amet congue egestas. Fusce aliquam erat leo, a tempor urna consequat quis. Integer dictum in ipsum a tincidunt. Etiam aliquet ipsum congue urna posuere, id euismod dui porta. In semper malesuada mollis.', image: 'https://i.wpimg.pl/985x0/m.autokult.pl/dsc-2874-3975d52abb5d042b2c7533a.jpg' },
      {id: 3, autor: 'anna@o2.pl',email:'anna@o2.pl', title: 'Phasellus ornare', created: new Date(2021,10,14,10,35), status: 'published', content: 'Sed tincidunt ac nunc eget hendrerit. Aenean egestas dignissim dictum. Morbi urna ligula, vulputate vel mi ac, eleifend posuere nisl. Maecenas tempor tellus in pellentesque dictum. Nullam eu est risus. Duis ac sollicitudin metus, id dapibus ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer non dolor blandit, consequat lectus ut, ultrices nisi. Integer gravida nisl eu leo maximus, quis venenatis est vehicula. Praesent mattis vestibulum porttitor. Suspendisse molestie consequat est, id dapibus metus finibus id.', image: 'https://storage.carsmile.pl/uploads/2021/04/thumb-mercedes_c_klasa_kombi-1000x520.jpg'},
      {id: 4, autor: 'agnf@gmail.com', email:'agnf@gmail.com',title: 'Nam vel libero', created: new Date(2021,10,22,12,45), status: 'published', content: ' Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque arcu risus, lobortis et arcu a, euismod ullamcorper dolor. Etiam quis diam commodo, dapibus tortor sit amet, molestie augue. Phasellus accumsan metus hendrerit vehicula lobortis. Donec ac molestie quam. Etiam at mauris non nibh pulvinar venenatis. Aliquam sed leo eu libero fermentum euismod. Suspendisse laoreet odio efficitur consequat sollicitudin. Sed aliquet, tortor sed condimentum fermentum, ex lacus fringilla neque, quis euismod ipsum nulla sit amet erat. ', image: 'https://storage.carsmile.pl/uploads/2019/10/carsmile_mazda_cx-30_foto1.png'},
      {id: 5, autor: 'agnf@gmail.com',email:'agnf@gmail.com',title: 'Maecenas at lectus', created: new Date(2021,9,8,9,35), status: 'published', content: 'Etiam pulvinar odio nibh, a gravida sapien bibendum ut. Fusce dolor elit, aliquam non volutpat non, tristique at sem. Fusce maximus mauris vel velit efficitur, sit amet bibendum magna mattis. Maecenas eget lectus a elit hendrerit malesuada. Mauris in erat placerat, tristique nibh non, placerat dui. Pellentesque at quam id urna pulvinar lacinia. Nunc convallis id nisl quis rutrum. Duis sollicitudin sagittis accumsan. Nam nisl purus, imperdiet ac libero a, aliquam volutpat ipsum. Sed vulputate volutpat est eu faucibus. Phasellus bibendum mattis nunc.', image: 'https://www.motowolf.pl/wp-content/uploads/2021/07/lamborghini-aventador-lp-780-4-ultimae-4.jpg'},
    ],
    loading: {
      active: false,
      error: false,
    },
    loggedUser:null,
    myPosts: false,
  },
};
